### ISSUE TITLE
Establish final draft of offchain writing ENSIP

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#150]
# Feature Request

Post the External Resolver ENSIP created by Blockful on the [ENS forum](discuss.ens.domains/). Adding updates based on L2 research of other implementations.

## Blocked by

#147 
#118 
#148
#149 

## Draft ([template](https://github.com/unruggable-labs/ENSIPs/blob/main/ensip-template.md))

**Comment by alextnetto** [comment]
---
title: <The ENSIP title is a few words, not a complete sentence>
description: <Description is one full (short) sentence>
author: <a comma separated list of the author's or authors' name + '/' ENS name + GitHub username (in parenthesis), or name and email (in angle brackets).  Example, FirstName LastName / ENS Name (@GitHubUsername), FirstName LastName / ENS Name <foo@bar.com>, FirstName / ENS Name (@GitHubUsername) and GitHubUsername / ENS Name (@GitHubUsername)>
discussions-to: <URL>
status: Draft
type: <Standards Track, Meta, or Informational>
category: <Core, ENSRC> # Only required for Standards Track. Otherwise, remove this field.
created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
requires: <ensip number(s)> # Only required when you reference an ENSIP in the `Specification` section. Otherwise, remove this field.
---



## Abstract



## Motivation



## Specification



The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119 and RFC 8174.

## Rationale



TBD

## Backwards Compatibility



No backward compatibility issues found.

## Test Cases



## Reference Implementation



## Security Considerations



Needs discussion.

## Copyright

Copyright and related rights waived via [CC0](../LICENSE.md).

**Comment by pikonha** [comment]
https://www.notion.so/blockful/ENSIP-16-b6a519e7d09047d2862bf5df17f088a5
